/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIMemoryProfile {
  'userId' : Principal,
  'lastUpdated' : Time,
  'preferences' : Array<[string, string]>,
  'toneVectors' : Array<[string, bigint]>,
  'goalPriorities' : Array<string>,
  'healthStats' : Array<[string, bigint]>,
  'communicationStyle' : string,
  'interactionHistory' : Array<string>,
}
export interface AgentInteraction {
  'message' : string,
  'response' : string,
  'timestamp' : Time,
}
export interface AnalyticsAggregate {
  'id' : string,
  'value' : bigint,
  'timestamp' : Time,
  'metricType' : string,
}
export interface Badge {
  'id' : string,
  'dateEarned' : Time,
  'name' : string,
  'description' : string,
}
export interface BrandSuggestion {
  'userEmail' : string,
  'timestamp' : Time,
  'category' : string,
  'brandName' : string,
  'reviewed' : boolean,
  'reason' : [] | [string],
}
export interface CheckoutSession {
  'id' : string,
  'status' : string,
  'paymentMethod' : string,
  'cart' : Array<Product>,
  'userId' : Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
  'totalAmount' : bigint,
}
export interface CoachingSession {
  'effectiveness' : bigint,
  'userResponse' : [] | [string],
  'userId' : Principal,
  'recommendations' : Array<string>,
  'timestamp' : Time,
  'sessionId' : string,
}
export interface CommunityProposal {
  'id' : string,
  'status' : string,
  'title' : string,
  'votes' : bigint,
  'createdAt' : Time,
  'description' : string,
  'proposer' : Principal,
}
export interface CustomMetric {
  'id' : string,
  'domain' : HealthDomain,
  'value' : bigint,
  'name' : string,
  'createdAt' : Time,
}
export interface DashboardPreference {
  'notificationPreferences' : Array<string>,
  'hiddenCards' : Array<string>,
  'userId' : Principal,
  'lastUpdated' : Time,
  'cardOrder' : Array<string>,
}
export interface DomainAgent {
  'insights' : Array<string>,
  'active' : boolean,
  'domain' : HealthDomain,
  'userId' : Principal,
  'recommendations' : Array<string>,
  'lastCheck' : Time,
}
export interface DomainProgress {
  'streak' : bigint,
  'lastUpdated' : Time,
  'score' : bigint,
}
export interface ExtractedField {
  'domain' : string,
  'value' : string,
  'source' : string,
  'indicator' : string,
  'confidence' : bigint,
  'fieldName' : string,
}
export interface FileReference { 'hash' : string, 'path' : string }
export interface GrantKPI {
  'id' : string,
  'value' : bigint,
  'period' : string,
  'timestamp' : Time,
  'metricName' : string,
}
export type HealthDomain = { 'mental' : null } |
  { 'longevity' : null } |
  { 'community' : null } |
  { 'fitness' : null } |
  { 'environment' : null } |
  { 'purpose' : null } |
  { 'nutrition' : null } |
  { 'finances' : null };
export interface HealthIndicator {
  'value' : bigint,
  'source' : string,
  'name' : string,
  'unit' : string,
  'timestamp' : Time,
}
export interface HealthProtocol {
  'id' : string,
  'status' : string,
  'timeframe' : bigint,
  'metrics' : Array<[string, bigint]>,
  'userId' : Principal,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'actions' : Array<string>,
  'version' : bigint,
  'goals' : Array<string>,
}
export interface HealthRecord {
  'id' : string,
  'status' : string,
  'userId' : Principal,
  'filePath' : string,
  'extractedData' : [] | [Array<ExtractedField>],
  'reviewStatus' : string,
  'fileType' : string,
  'uploadTime' : Time,
}
export interface HelpPreference {
  'userId' : Principal,
  'lastUpdated' : Time,
  'showHelp' : boolean,
  'completedTutorials' : Array<string>,
}
export interface LeaderboardEntry {
  'domain' : HealthDomain,
  'userId' : string,
  'score' : bigint,
}
export interface LiquidityPool {
  'id' : string,
  'apy' : bigint,
  'totalLiquidity' : bigint,
  'volume' : bigint,
  'tokenPair' : string,
}
export interface Notification {
  'id' : string,
  'read' : boolean,
  'type' : string,
  'message' : string,
  'dateSent' : Time,
}
export interface NotificationPreference {
  'enabledTypes' : Array<string>,
  'userId' : Principal,
  'quietHours' : Array<[bigint, bigint]>,
  'tone' : string,
  'lastUpdated' : Time,
  'frequency' : string,
}
export interface PartnerIntegration {
  'id' : string,
  'status' : string,
  'partnerName' : string,
  'createdAt' : Time,
  'integrationType' : string,
}
export interface PaymentTransaction {
  'id' : string,
  'status' : string,
  'paymentMethod' : string,
  'userId' : Principal,
  'errorMessage' : [] | [string],
  'vendor' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface PerformanceMetric {
  'id' : string,
  'value' : bigint,
  'canister' : string,
  'timestamp' : Time,
  'metricType' : string,
}
export interface Product {
  'id' : string,
  'protocol' : string,
  'name' : string,
  'recommended' : boolean,
  'description' : string,
  'aiInfo' : string,
  'vendor' : string,
  'category' : string,
  'price' : bigint,
  'ranking' : bigint,
}
export interface ProfessionalAccessToken {
  'permissions' : Array<string>,
  'active' : boolean,
  'tokenId' : string,
  'expiresAt' : Time,
  'userId' : Principal,
  'createdAt' : Time,
  'professionalId' : Principal,
}
export interface PromptSuggestion {
  'id' : string,
  'context' : string,
  'usageCount' : bigint,
  'prompt' : string,
  'lastUsed' : Time,
}
export interface ProtocolProgress {
  'currentMetrics' : Array<[string, bigint]>,
  'userId' : Principal,
  'lastUpdated' : Time,
  'protocolId' : string,
  'completedActions' : Array<string>,
  'milestones' : Array<[string, boolean]>,
}
export interface QuickAction {
  'id' : string,
  'action' : string,
  'context' : string,
  'usageCount' : bigint,
  'lastUsed' : Time,
}
export interface Referral {
  'referrer' : Principal,
  'rewardClaimed' : boolean,
  'code' : string,
  'timestamp' : Time,
  'referee' : [] | [Principal],
}
export interface Reward {
  'id' : string,
  'type' : string,
  'dateAwarded' : Time,
  'amount' : bigint,
}
export interface ScheduledNotification {
  'id' : string,
  'status' : string,
  'scheduledTime' : Time,
  'userId' : Principal,
  'createdAt' : Time,
  'message' : string,
  'sentimentIntensity' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StakingPosition {
  'startTime' : Time,
  'active' : boolean,
  'userId' : Principal,
  'amount' : bigint,
  'lockupPeriod' : bigint,
  'rewardMultiplier' : bigint,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SystemMetric {
  'id' : string,
  'cycleUsage' : bigint,
  'userEngagement' : bigint,
  'timestamp' : Time,
  'aiProcessingTime' : bigint,
  'proofsPerDay' : bigint,
  'stakingTotals' : bigint,
}
export type Time = bigint;
export interface TourProgress {
  'userId' : Principal,
  'completed' : boolean,
  'lastUpdated' : Time,
  'steps' : Array<TourStep>,
}
export interface TourStep {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'completed' : boolean,
  'description' : string,
  'target' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TransparencyLog {
  'id' : string,
  'status' : string,
  'action' : string,
  'userId' : Principal,
  'dataHash' : string,
  'timestamp' : Time,
}
export interface UploadStatus {
  'id' : string,
  'status' : string,
  'userId' : Principal,
  'errorMessage' : [] | [string],
  'filePath' : string,
  'progress' : bigint,
  'timestamp' : Time,
}
export interface UserProfile {
  'age' : bigint,
  'name' : string,
  'onboardingComplete' : boolean,
  'agentName' : string,
  'subscriptionStatus' : boolean,
  'goals' : Array<string>,
  'healthConcerns' : Array<string>,
  'privacyConsent' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WearableConnection {
  'service' : string,
  'expiresAt' : [] | [Time],
  'refreshToken' : [] | [string],
  'connectedAt' : Time,
  'accessToken' : string,
}
export interface WhitePaperDocument {
  'id' : string,
  'status' : string,
  'title' : string,
  'createdAt' : Time,
  'version' : bigint,
  'updatedAt' : Time,
  'sections' : Array<WhitePaperSection>,
}
export interface WhitePaperSection {
  'id' : string,
  'title' : string,
  'content' : string,
  'order' : bigint,
  'lastUpdated' : Time,
}
export interface ZKProof {
  'id' : string,
  'verified' : boolean,
  'proofData' : string,
  'userId' : Principal,
  'timestamp' : Time,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addAgentInteraction' : ActorMethod<[AgentInteraction], undefined>,
  'addBadge' : ActorMethod<[Badge], undefined>,
  'addCoachingSession' : ActorMethod<[CoachingSession], undefined>,
  'addDomainAgent' : ActorMethod<[DomainAgent], undefined>,
  'addExtractedData' : ActorMethod<[string, Array<ExtractedField>], undefined>,
  'addHealthIndicator' : ActorMethod<[HealthIndicator], undefined>,
  'addLeaderboardEntry' : ActorMethod<[LeaderboardEntry], undefined>,
  'addNotification' : ActorMethod<[Principal, Notification], undefined>,
  'addPartnerIntegration' : ActorMethod<[string, string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addReward' : ActorMethod<[Reward], undefined>,
  'addWhitePaperSection' : ActorMethod<[string, WhitePaperSection], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimReferralReward' : ActorMethod<[string], undefined>,
  'completeOnboarding' : ActorMethod<[], undefined>,
  'connectWearable' : ActorMethod<
    [string, string, [] | [string], [] | [Time]],
    undefined
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCustomCheckoutSession' : ActorMethod<
    [Array<Product>, bigint, string],
    string
  >,
  'createCustomMetric' : ActorMethod<[CustomMetric], undefined>,
  'createHealthProtocol' : ActorMethod<[HealthProtocol], undefined>,
  'createProfessionalAccessToken' : ActorMethod<
    [ProfessionalAccessToken],
    undefined
  >,
  'createReferral' : ActorMethod<[string], undefined>,
  'createWhitePaperDocument' : ActorMethod<[string], string>,
  'deleteCheckoutSession' : ActorMethod<[string], undefined>,
  'deleteHealthRecord' : ActorMethod<[string], undefined>,
  'deletePaymentTransaction' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteUploadStatus' : ActorMethod<[string], undefined>,
  'deleteWhitePaperDocument' : ActorMethod<[string], undefined>,
  'deleteWhitePaperSection' : ActorMethod<[string, string], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'getAIMemoryProfile' : ActorMethod<[], [] | [AIMemoryProfile]>,
  'getAgentInteractions' : ActorMethod<[], Array<AgentInteraction>>,
  'getAllReferrals' : ActorMethod<[], Array<Referral>>,
  'getAllWhitePaperDocuments' : ActorMethod<[], Array<WhitePaperDocument>>,
  'getAnalyticsAggregates' : ActorMethod<[], Array<AnalyticsAggregate>>,
  'getBadges' : ActorMethod<[], Array<Badge>>,
  'getBrandSuggestions' : ActorMethod<[], Array<BrandSuggestion>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheckoutSessionById' : ActorMethod<[string], [] | [CheckoutSession]>,
  'getCheckoutSessions' : ActorMethod<[], Array<CheckoutSession>>,
  'getCoachingSessions' : ActorMethod<[], Array<CoachingSession>>,
  'getCommunityProposals' : ActorMethod<[], Array<CommunityProposal>>,
  'getCustomMetrics' : ActorMethod<[], Array<CustomMetric>>,
  'getDashboardPreferences' : ActorMethod<[], [] | [DashboardPreference]>,
  'getDomainAgents' : ActorMethod<[], Array<DomainAgent>>,
  'getDomainProgress' : ActorMethod<[], Array<[HealthDomain, DomainProgress]>>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getGrantKPIs' : ActorMethod<[], Array<GrantKPI>>,
  'getHealthIndicators' : ActorMethod<[], Array<HealthIndicator>>,
  'getHealthProtocol' : ActorMethod<[string], [] | [HealthProtocol]>,
  'getHealthRecordById' : ActorMethod<[string], [] | [HealthRecord]>,
  'getHealthRecords' : ActorMethod<[], Array<HealthRecord>>,
  'getHelpPreferences' : ActorMethod<[], [] | [HelpPreference]>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getLiquidityPools' : ActorMethod<[], Array<LiquidityPool>>,
  'getNotificationPreferences' : ActorMethod<[], [] | [NotificationPreference]>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPartnerIntegrations' : ActorMethod<[], Array<PartnerIntegration>>,
  'getPaymentTransactionById' : ActorMethod<
    [string],
    [] | [PaymentTransaction]
  >,
  'getPaymentTransactions' : ActorMethod<[], Array<PaymentTransaction>>,
  'getPerformanceMetrics' : ActorMethod<[], Array<PerformanceMetric>>,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProfessionalAccessToken' : ActorMethod<
    [string],
    [] | [ProfessionalAccessToken]
  >,
  'getPromptSuggestions' : ActorMethod<[], Array<PromptSuggestion>>,
  'getProtocolProgress' : ActorMethod<[string], [] | [ProtocolProgress]>,
  'getPublicSystemMetrics' : ActorMethod<[], Array<SystemMetric>>,
  'getQuickActions' : ActorMethod<[], Array<QuickAction>>,
  'getReferral' : ActorMethod<[string], [] | [Referral]>,
  'getRewards' : ActorMethod<[], Array<Reward>>,
  'getScheduledNotifications' : ActorMethod<[], Array<ScheduledNotification>>,
  'getStakingPositions' : ActorMethod<[], Array<StakingPosition>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSystemMetrics' : ActorMethod<[], Array<SystemMetric>>,
  'getTourProgress' : ActorMethod<[], [] | [TourProgress]>,
  'getTransparencyLogs' : ActorMethod<[], Array<TransparencyLog>>,
  'getUploadStatusById' : ActorMethod<[string], [] | [UploadStatus]>,
  'getUploadStatuses' : ActorMethod<[], Array<UploadStatus>>,
  'getUserHealthProtocols' : ActorMethod<[], Array<HealthProtocol>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWearableConnections' : ActorMethod<[], Array<WearableConnection>>,
  'getWhitePaperDocument' : ActorMethod<[string], [] | [WhitePaperDocument]>,
  'getZKProofs' : ActorMethod<[], Array<ZKProof>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isBlackboardLocked' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOnboardingComplete' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'lockBlackboard' : ActorMethod<[], string>,
  'logTransparencyAction' : ActorMethod<[string, string, string], undefined>,
  'processPayment' : ActorMethod<[bigint, string, string], string>,
  'recordAnalyticsAggregate' : ActorMethod<[string, bigint], undefined>,
  'recordGrantKPI' : ActorMethod<[GrantKPI], undefined>,
  'recordPerformanceMetric' : ActorMethod<[string, string, bigint], undefined>,
  'recordSystemMetric' : ActorMethod<[SystemMetric], undefined>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'revokeProfessionalAccessToken' : ActorMethod<[string], undefined>,
  'saveAIMemoryProfile' : ActorMethod<[AIMemoryProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDashboardPreferences' : ActorMethod<[DashboardPreference], undefined>,
  'saveHelpPreferences' : ActorMethod<[HelpPreference], undefined>,
  'saveNotificationPreferences' : ActorMethod<
    [NotificationPreference],
    undefined
  >,
  'savePromptSuggestions' : ActorMethod<[Array<PromptSuggestion>], undefined>,
  'saveQuickActions' : ActorMethod<[Array<QuickAction>], undefined>,
  'saveTourProgress' : ActorMethod<[TourProgress], undefined>,
  'scheduleNotification' : ActorMethod<[ScheduledNotification], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'stakeTokens' : ActorMethod<[bigint, bigint], undefined>,
  'submitBrandSuggestion' : ActorMethod<
    [string, string, [] | [string], string],
    undefined
  >,
  'submitCommunityProposal' : ActorMethod<[string, string], undefined>,
  'submitZKProof' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unlockBlackboard' : ActorMethod<[], string>,
  'unstakeTokens' : ActorMethod<[bigint], undefined>,
  'updateCheckoutSession' : ActorMethod<[string, CheckoutSession], undefined>,
  'updateDomainProgress' : ActorMethod<
    [HealthDomain, DomainProgress],
    undefined
  >,
  'updateLiquidityPools' : ActorMethod<[], undefined>,
  'updatePaymentTransaction' : ActorMethod<
    [string, PaymentTransaction],
    undefined
  >,
  'updateProduct' : ActorMethod<[string, Product], undefined>,
  'updateProtocolProgress' : ActorMethod<[ProtocolProgress], undefined>,
  'updateReviewStatus' : ActorMethod<[string, string], undefined>,
  'updateUploadStatus' : ActorMethod<
    [string, string, bigint, [] | [string]],
    undefined
  >,
  'updateWhitePaperSection' : ActorMethod<
    [string, string, WhitePaperSection],
    undefined
  >,
  'updateWhitePaperStatus' : ActorMethod<[string, string], undefined>,
  'uploadHealthRecord' : ActorMethod<[string, string], string>,
  'voteOnProposal' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];