/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AgentInteraction = IDL.Record({
  'message' : IDL.Text,
  'response' : IDL.Text,
  'timestamp' : Time,
});
export const Badge = IDL.Record({
  'id' : IDL.Text,
  'dateEarned' : Time,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const CoachingSession = IDL.Record({
  'effectiveness' : IDL.Nat,
  'userResponse' : IDL.Opt(IDL.Text),
  'userId' : IDL.Principal,
  'recommendations' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'sessionId' : IDL.Text,
});
export const HealthDomain = IDL.Variant({
  'mental' : IDL.Null,
  'longevity' : IDL.Null,
  'community' : IDL.Null,
  'fitness' : IDL.Null,
  'environment' : IDL.Null,
  'purpose' : IDL.Null,
  'nutrition' : IDL.Null,
  'finances' : IDL.Null,
});
export const DomainAgent = IDL.Record({
  'insights' : IDL.Vec(IDL.Text),
  'active' : IDL.Bool,
  'domain' : HealthDomain,
  'userId' : IDL.Principal,
  'recommendations' : IDL.Vec(IDL.Text),
  'lastCheck' : Time,
});
export const ExtractedField = IDL.Record({
  'domain' : IDL.Text,
  'value' : IDL.Text,
  'source' : IDL.Text,
  'indicator' : IDL.Text,
  'confidence' : IDL.Nat,
  'fieldName' : IDL.Text,
});
export const HealthIndicator = IDL.Record({
  'value' : IDL.Nat,
  'source' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'timestamp' : Time,
});
export const LeaderboardEntry = IDL.Record({
  'domain' : HealthDomain,
  'userId' : IDL.Text,
  'score' : IDL.Nat,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'read' : IDL.Bool,
  'type' : IDL.Text,
  'message' : IDL.Text,
  'dateSent' : Time,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'protocol' : IDL.Text,
  'name' : IDL.Text,
  'recommended' : IDL.Bool,
  'description' : IDL.Text,
  'aiInfo' : IDL.Text,
  'vendor' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'ranking' : IDL.Nat,
});
export const Reward = IDL.Record({
  'id' : IDL.Text,
  'type' : IDL.Text,
  'dateAwarded' : Time,
  'amount' : IDL.Nat,
});
export const WhitePaperSection = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'lastUpdated' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CustomMetric = IDL.Record({
  'id' : IDL.Text,
  'domain' : HealthDomain,
  'value' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const HealthProtocol = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'timeframe' : IDL.Nat,
  'metrics' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'actions' : IDL.Vec(IDL.Text),
  'version' : IDL.Nat,
  'goals' : IDL.Vec(IDL.Text),
});
export const ProfessionalAccessToken = IDL.Record({
  'permissions' : IDL.Vec(IDL.Text),
  'active' : IDL.Bool,
  'tokenId' : IDL.Text,
  'expiresAt' : Time,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'professionalId' : IDL.Principal,
});
export const AIMemoryProfile = IDL.Record({
  'userId' : IDL.Principal,
  'lastUpdated' : Time,
  'preferences' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'toneVectors' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'goalPriorities' : IDL.Vec(IDL.Text),
  'healthStats' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'communicationStyle' : IDL.Text,
  'interactionHistory' : IDL.Vec(IDL.Text),
});
export const Referral = IDL.Record({
  'referrer' : IDL.Principal,
  'rewardClaimed' : IDL.Bool,
  'code' : IDL.Text,
  'timestamp' : Time,
  'referee' : IDL.Opt(IDL.Principal),
});
export const WhitePaperDocument = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'version' : IDL.Nat,
  'updatedAt' : Time,
  'sections' : IDL.Vec(WhitePaperSection),
});
export const AnalyticsAggregate = IDL.Record({
  'id' : IDL.Text,
  'value' : IDL.Nat,
  'timestamp' : Time,
  'metricType' : IDL.Text,
});
export const BrandSuggestion = IDL.Record({
  'userEmail' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'brandName' : IDL.Text,
  'reviewed' : IDL.Bool,
  'reason' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'onboardingComplete' : IDL.Bool,
  'agentName' : IDL.Text,
  'subscriptionStatus' : IDL.Bool,
  'goals' : IDL.Vec(IDL.Text),
  'healthConcerns' : IDL.Vec(IDL.Text),
  'privacyConsent' : IDL.Bool,
});
export const CheckoutSession = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'cart' : IDL.Vec(Product),
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
  'totalAmount' : IDL.Nat,
});
export const CommunityProposal = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'votes' : IDL.Nat,
  'createdAt' : Time,
  'description' : IDL.Text,
  'proposer' : IDL.Principal,
});
export const DashboardPreference = IDL.Record({
  'notificationPreferences' : IDL.Vec(IDL.Text),
  'hiddenCards' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
  'lastUpdated' : Time,
  'cardOrder' : IDL.Vec(IDL.Text),
});
export const DomainProgress = IDL.Record({
  'streak' : IDL.Nat,
  'lastUpdated' : Time,
  'score' : IDL.Nat,
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const GrantKPI = IDL.Record({
  'id' : IDL.Text,
  'value' : IDL.Nat,
  'period' : IDL.Text,
  'timestamp' : Time,
  'metricName' : IDL.Text,
});
export const HealthRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'filePath' : IDL.Text,
  'extractedData' : IDL.Opt(IDL.Vec(ExtractedField)),
  'reviewStatus' : IDL.Text,
  'fileType' : IDL.Text,
  'uploadTime' : Time,
});
export const HelpPreference = IDL.Record({
  'userId' : IDL.Principal,
  'lastUpdated' : Time,
  'showHelp' : IDL.Bool,
  'completedTutorials' : IDL.Vec(IDL.Text),
});
export const LiquidityPool = IDL.Record({
  'id' : IDL.Text,
  'apy' : IDL.Nat,
  'totalLiquidity' : IDL.Nat,
  'volume' : IDL.Nat,
  'tokenPair' : IDL.Text,
});
export const NotificationPreference = IDL.Record({
  'enabledTypes' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
  'quietHours' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'tone' : IDL.Text,
  'lastUpdated' : Time,
  'frequency' : IDL.Text,
});
export const PartnerIntegration = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'partnerName' : IDL.Text,
  'createdAt' : Time,
  'integrationType' : IDL.Text,
});
export const PaymentTransaction = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'userId' : IDL.Principal,
  'errorMessage' : IDL.Opt(IDL.Text),
  'vendor' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const PerformanceMetric = IDL.Record({
  'id' : IDL.Text,
  'value' : IDL.Nat,
  'canister' : IDL.Text,
  'timestamp' : Time,
  'metricType' : IDL.Text,
});
export const PromptSuggestion = IDL.Record({
  'id' : IDL.Text,
  'context' : IDL.Text,
  'usageCount' : IDL.Nat,
  'prompt' : IDL.Text,
  'lastUsed' : Time,
});
export const ProtocolProgress = IDL.Record({
  'currentMetrics' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'userId' : IDL.Principal,
  'lastUpdated' : Time,
  'protocolId' : IDL.Text,
  'completedActions' : IDL.Vec(IDL.Text),
  'milestones' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
});
export const SystemMetric = IDL.Record({
  'id' : IDL.Text,
  'cycleUsage' : IDL.Nat,
  'userEngagement' : IDL.Nat,
  'timestamp' : Time,
  'aiProcessingTime' : IDL.Nat,
  'proofsPerDay' : IDL.Nat,
  'stakingTotals' : IDL.Nat,
});
export const QuickAction = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'context' : IDL.Text,
  'usageCount' : IDL.Nat,
  'lastUsed' : Time,
});
export const ScheduledNotification = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'scheduledTime' : Time,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'message' : IDL.Text,
  'sentimentIntensity' : IDL.Text,
});
export const StakingPosition = IDL.Record({
  'startTime' : Time,
  'active' : IDL.Bool,
  'userId' : IDL.Principal,
  'amount' : IDL.Nat,
  'lockupPeriod' : IDL.Nat,
  'rewardMultiplier' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TourStep = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'target' : IDL.Text,
});
export const TourProgress = IDL.Record({
  'userId' : IDL.Principal,
  'completed' : IDL.Bool,
  'lastUpdated' : Time,
  'steps' : IDL.Vec(TourStep),
});
export const TransparencyLog = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'action' : IDL.Text,
  'userId' : IDL.Principal,
  'dataHash' : IDL.Text,
  'timestamp' : Time,
});
export const UploadStatus = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'errorMessage' : IDL.Opt(IDL.Text),
  'filePath' : IDL.Text,
  'progress' : IDL.Nat,
  'timestamp' : Time,
});
export const WearableConnection = IDL.Record({
  'service' : IDL.Text,
  'expiresAt' : IDL.Opt(Time),
  'refreshToken' : IDL.Opt(IDL.Text),
  'connectedAt' : Time,
  'accessToken' : IDL.Text,
});
export const ZKProof = IDL.Record({
  'id' : IDL.Text,
  'verified' : IDL.Bool,
  'proofData' : IDL.Text,
  'userId' : IDL.Principal,
  'timestamp' : Time,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addAgentInteraction' : IDL.Func([AgentInteraction], [], []),
  'addBadge' : IDL.Func([Badge], [], []),
  'addCoachingSession' : IDL.Func([CoachingSession], [], []),
  'addDomainAgent' : IDL.Func([DomainAgent], [], []),
  'addExtractedData' : IDL.Func([IDL.Text, IDL.Vec(ExtractedField)], [], []),
  'addHealthIndicator' : IDL.Func([HealthIndicator], [], []),
  'addLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
  'addNotification' : IDL.Func([IDL.Principal, Notification], [], []),
  'addPartnerIntegration' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addReward' : IDL.Func([Reward], [], []),
  'addWhitePaperSection' : IDL.Func([IDL.Text, WhitePaperSection], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimReferralReward' : IDL.Func([IDL.Text], [], []),
  'completeOnboarding' : IDL.Func([], [], []),
  'connectWearable' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(Time)],
      [],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCustomCheckoutSession' : IDL.Func(
      [IDL.Vec(Product), IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCustomMetric' : IDL.Func([CustomMetric], [], []),
  'createHealthProtocol' : IDL.Func([HealthProtocol], [], []),
  'createProfessionalAccessToken' : IDL.Func([ProfessionalAccessToken], [], []),
  'createReferral' : IDL.Func([IDL.Text], [], []),
  'createWhitePaperDocument' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteCheckoutSession' : IDL.Func([IDL.Text], [], []),
  'deleteHealthRecord' : IDL.Func([IDL.Text], [], []),
  'deletePaymentTransaction' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteUploadStatus' : IDL.Func([IDL.Text], [], []),
  'deleteWhitePaperDocument' : IDL.Func([IDL.Text], [], []),
  'deleteWhitePaperSection' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'getAIMemoryProfile' : IDL.Func([], [IDL.Opt(AIMemoryProfile)], ['query']),
  'getAgentInteractions' : IDL.Func([], [IDL.Vec(AgentInteraction)], ['query']),
  'getAllReferrals' : IDL.Func([], [IDL.Vec(Referral)], ['query']),
  'getAllWhitePaperDocuments' : IDL.Func(
      [],
      [IDL.Vec(WhitePaperDocument)],
      ['query'],
    ),
  'getAnalyticsAggregates' : IDL.Func(
      [],
      [IDL.Vec(AnalyticsAggregate)],
      ['query'],
    ),
  'getBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
  'getBrandSuggestions' : IDL.Func([], [IDL.Vec(BrandSuggestion)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckoutSessionById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CheckoutSession)],
      ['query'],
    ),
  'getCheckoutSessions' : IDL.Func([], [IDL.Vec(CheckoutSession)], ['query']),
  'getCoachingSessions' : IDL.Func([], [IDL.Vec(CoachingSession)], ['query']),
  'getCommunityProposals' : IDL.Func(
      [],
      [IDL.Vec(CommunityProposal)],
      ['query'],
    ),
  'getCustomMetrics' : IDL.Func([], [IDL.Vec(CustomMetric)], ['query']),
  'getDashboardPreferences' : IDL.Func(
      [],
      [IDL.Opt(DashboardPreference)],
      ['query'],
    ),
  'getDomainAgents' : IDL.Func([], [IDL.Vec(DomainAgent)], ['query']),
  'getDomainProgress' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(HealthDomain, DomainProgress))],
      ['query'],
    ),
  'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
  'getGrantKPIs' : IDL.Func([], [IDL.Vec(GrantKPI)], ['query']),
  'getHealthIndicators' : IDL.Func([], [IDL.Vec(HealthIndicator)], ['query']),
  'getHealthProtocol' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(HealthProtocol)],
      ['query'],
    ),
  'getHealthRecordById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(HealthRecord)],
      ['query'],
    ),
  'getHealthRecords' : IDL.Func([], [IDL.Vec(HealthRecord)], ['query']),
  'getHelpPreferences' : IDL.Func([], [IDL.Opt(HelpPreference)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getLiquidityPools' : IDL.Func([], [IDL.Vec(LiquidityPool)], ['query']),
  'getNotificationPreferences' : IDL.Func(
      [],
      [IDL.Opt(NotificationPreference)],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPartnerIntegrations' : IDL.Func(
      [],
      [IDL.Vec(PartnerIntegration)],
      ['query'],
    ),
  'getPaymentTransactionById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PaymentTransaction)],
      ['query'],
    ),
  'getPaymentTransactions' : IDL.Func(
      [],
      [IDL.Vec(PaymentTransaction)],
      ['query'],
    ),
  'getPerformanceMetrics' : IDL.Func(
      [],
      [IDL.Vec(PerformanceMetric)],
      ['query'],
    ),
  'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProfessionalAccessToken' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ProfessionalAccessToken)],
      ['query'],
    ),
  'getPromptSuggestions' : IDL.Func([], [IDL.Vec(PromptSuggestion)], ['query']),
  'getProtocolProgress' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ProtocolProgress)],
      ['query'],
    ),
  'getPublicSystemMetrics' : IDL.Func([], [IDL.Vec(SystemMetric)], ['query']),
  'getQuickActions' : IDL.Func([], [IDL.Vec(QuickAction)], ['query']),
  'getReferral' : IDL.Func([IDL.Text], [IDL.Opt(Referral)], ['query']),
  'getRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
  'getScheduledNotifications' : IDL.Func(
      [],
      [IDL.Vec(ScheduledNotification)],
      ['query'],
    ),
  'getStakingPositions' : IDL.Func([], [IDL.Vec(StakingPosition)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSystemMetrics' : IDL.Func([], [IDL.Vec(SystemMetric)], ['query']),
  'getTourProgress' : IDL.Func([], [IDL.Opt(TourProgress)], ['query']),
  'getTransparencyLogs' : IDL.Func([], [IDL.Vec(TransparencyLog)], ['query']),
  'getUploadStatusById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UploadStatus)],
      ['query'],
    ),
  'getUploadStatuses' : IDL.Func([], [IDL.Vec(UploadStatus)], ['query']),
  'getUserHealthProtocols' : IDL.Func([], [IDL.Vec(HealthProtocol)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWearableConnections' : IDL.Func(
      [],
      [IDL.Vec(WearableConnection)],
      ['query'],
    ),
  'getWhitePaperDocument' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WhitePaperDocument)],
      ['query'],
    ),
  'getZKProofs' : IDL.Func([], [IDL.Vec(ZKProof)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isBlackboardLocked' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOnboardingComplete' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'lockBlackboard' : IDL.Func([], [IDL.Text], []),
  'logTransparencyAction' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'processPayment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Text], []),
  'recordAnalyticsAggregate' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'recordGrantKPI' : IDL.Func([GrantKPI], [], []),
  'recordPerformanceMetric' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'recordSystemMetric' : IDL.Func([SystemMetric], [], []),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'revokeProfessionalAccessToken' : IDL.Func([IDL.Text], [], []),
  'saveAIMemoryProfile' : IDL.Func([AIMemoryProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDashboardPreferences' : IDL.Func([DashboardPreference], [], []),
  'saveHelpPreferences' : IDL.Func([HelpPreference], [], []),
  'saveNotificationPreferences' : IDL.Func([NotificationPreference], [], []),
  'savePromptSuggestions' : IDL.Func([IDL.Vec(PromptSuggestion)], [], []),
  'saveQuickActions' : IDL.Func([IDL.Vec(QuickAction)], [], []),
  'saveTourProgress' : IDL.Func([TourProgress], [], []),
  'scheduleNotification' : IDL.Func([ScheduledNotification], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'stakeTokens' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'submitBrandSuggestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'submitCommunityProposal' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitZKProof' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unlockBlackboard' : IDL.Func([], [IDL.Text], []),
  'unstakeTokens' : IDL.Func([IDL.Nat], [], []),
  'updateCheckoutSession' : IDL.Func([IDL.Text, CheckoutSession], [], []),
  'updateDomainProgress' : IDL.Func([HealthDomain, DomainProgress], [], []),
  'updateLiquidityPools' : IDL.Func([], [], []),
  'updatePaymentTransaction' : IDL.Func([IDL.Text, PaymentTransaction], [], []),
  'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
  'updateProtocolProgress' : IDL.Func([ProtocolProgress], [], []),
  'updateReviewStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateUploadStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateWhitePaperSection' : IDL.Func(
      [IDL.Text, IDL.Text, WhitePaperSection],
      [],
      [],
    ),
  'updateWhitePaperStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'uploadHealthRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'voteOnProposal' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AgentInteraction = IDL.Record({
    'message' : IDL.Text,
    'response' : IDL.Text,
    'timestamp' : Time,
  });
  const Badge = IDL.Record({
    'id' : IDL.Text,
    'dateEarned' : Time,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const CoachingSession = IDL.Record({
    'effectiveness' : IDL.Nat,
    'userResponse' : IDL.Opt(IDL.Text),
    'userId' : IDL.Principal,
    'recommendations' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'sessionId' : IDL.Text,
  });
  const HealthDomain = IDL.Variant({
    'mental' : IDL.Null,
    'longevity' : IDL.Null,
    'community' : IDL.Null,
    'fitness' : IDL.Null,
    'environment' : IDL.Null,
    'purpose' : IDL.Null,
    'nutrition' : IDL.Null,
    'finances' : IDL.Null,
  });
  const DomainAgent = IDL.Record({
    'insights' : IDL.Vec(IDL.Text),
    'active' : IDL.Bool,
    'domain' : HealthDomain,
    'userId' : IDL.Principal,
    'recommendations' : IDL.Vec(IDL.Text),
    'lastCheck' : Time,
  });
  const ExtractedField = IDL.Record({
    'domain' : IDL.Text,
    'value' : IDL.Text,
    'source' : IDL.Text,
    'indicator' : IDL.Text,
    'confidence' : IDL.Nat,
    'fieldName' : IDL.Text,
  });
  const HealthIndicator = IDL.Record({
    'value' : IDL.Nat,
    'source' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'timestamp' : Time,
  });
  const LeaderboardEntry = IDL.Record({
    'domain' : HealthDomain,
    'userId' : IDL.Text,
    'score' : IDL.Nat,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'read' : IDL.Bool,
    'type' : IDL.Text,
    'message' : IDL.Text,
    'dateSent' : Time,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'protocol' : IDL.Text,
    'name' : IDL.Text,
    'recommended' : IDL.Bool,
    'description' : IDL.Text,
    'aiInfo' : IDL.Text,
    'vendor' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'ranking' : IDL.Nat,
  });
  const Reward = IDL.Record({
    'id' : IDL.Text,
    'type' : IDL.Text,
    'dateAwarded' : Time,
    'amount' : IDL.Nat,
  });
  const WhitePaperSection = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'lastUpdated' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CustomMetric = IDL.Record({
    'id' : IDL.Text,
    'domain' : HealthDomain,
    'value' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const HealthProtocol = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'timeframe' : IDL.Nat,
    'metrics' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'actions' : IDL.Vec(IDL.Text),
    'version' : IDL.Nat,
    'goals' : IDL.Vec(IDL.Text),
  });
  const ProfessionalAccessToken = IDL.Record({
    'permissions' : IDL.Vec(IDL.Text),
    'active' : IDL.Bool,
    'tokenId' : IDL.Text,
    'expiresAt' : Time,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'professionalId' : IDL.Principal,
  });
  const AIMemoryProfile = IDL.Record({
    'userId' : IDL.Principal,
    'lastUpdated' : Time,
    'preferences' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'toneVectors' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'goalPriorities' : IDL.Vec(IDL.Text),
    'healthStats' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'communicationStyle' : IDL.Text,
    'interactionHistory' : IDL.Vec(IDL.Text),
  });
  const Referral = IDL.Record({
    'referrer' : IDL.Principal,
    'rewardClaimed' : IDL.Bool,
    'code' : IDL.Text,
    'timestamp' : Time,
    'referee' : IDL.Opt(IDL.Principal),
  });
  const WhitePaperDocument = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'version' : IDL.Nat,
    'updatedAt' : Time,
    'sections' : IDL.Vec(WhitePaperSection),
  });
  const AnalyticsAggregate = IDL.Record({
    'id' : IDL.Text,
    'value' : IDL.Nat,
    'timestamp' : Time,
    'metricType' : IDL.Text,
  });
  const BrandSuggestion = IDL.Record({
    'userEmail' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'brandName' : IDL.Text,
    'reviewed' : IDL.Bool,
    'reason' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'onboardingComplete' : IDL.Bool,
    'agentName' : IDL.Text,
    'subscriptionStatus' : IDL.Bool,
    'goals' : IDL.Vec(IDL.Text),
    'healthConcerns' : IDL.Vec(IDL.Text),
    'privacyConsent' : IDL.Bool,
  });
  const CheckoutSession = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'cart' : IDL.Vec(Product),
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'updatedAt' : Time,
    'totalAmount' : IDL.Nat,
  });
  const CommunityProposal = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'votes' : IDL.Nat,
    'createdAt' : Time,
    'description' : IDL.Text,
    'proposer' : IDL.Principal,
  });
  const DashboardPreference = IDL.Record({
    'notificationPreferences' : IDL.Vec(IDL.Text),
    'hiddenCards' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
    'lastUpdated' : Time,
    'cardOrder' : IDL.Vec(IDL.Text),
  });
  const DomainProgress = IDL.Record({
    'streak' : IDL.Nat,
    'lastUpdated' : Time,
    'score' : IDL.Nat,
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const GrantKPI = IDL.Record({
    'id' : IDL.Text,
    'value' : IDL.Nat,
    'period' : IDL.Text,
    'timestamp' : Time,
    'metricName' : IDL.Text,
  });
  const HealthRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'filePath' : IDL.Text,
    'extractedData' : IDL.Opt(IDL.Vec(ExtractedField)),
    'reviewStatus' : IDL.Text,
    'fileType' : IDL.Text,
    'uploadTime' : Time,
  });
  const HelpPreference = IDL.Record({
    'userId' : IDL.Principal,
    'lastUpdated' : Time,
    'showHelp' : IDL.Bool,
    'completedTutorials' : IDL.Vec(IDL.Text),
  });
  const LiquidityPool = IDL.Record({
    'id' : IDL.Text,
    'apy' : IDL.Nat,
    'totalLiquidity' : IDL.Nat,
    'volume' : IDL.Nat,
    'tokenPair' : IDL.Text,
  });
  const NotificationPreference = IDL.Record({
    'enabledTypes' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
    'quietHours' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'tone' : IDL.Text,
    'lastUpdated' : Time,
    'frequency' : IDL.Text,
  });
  const PartnerIntegration = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'partnerName' : IDL.Text,
    'createdAt' : Time,
    'integrationType' : IDL.Text,
  });
  const PaymentTransaction = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'userId' : IDL.Principal,
    'errorMessage' : IDL.Opt(IDL.Text),
    'vendor' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const PerformanceMetric = IDL.Record({
    'id' : IDL.Text,
    'value' : IDL.Nat,
    'canister' : IDL.Text,
    'timestamp' : Time,
    'metricType' : IDL.Text,
  });
  const PromptSuggestion = IDL.Record({
    'id' : IDL.Text,
    'context' : IDL.Text,
    'usageCount' : IDL.Nat,
    'prompt' : IDL.Text,
    'lastUsed' : Time,
  });
  const ProtocolProgress = IDL.Record({
    'currentMetrics' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'userId' : IDL.Principal,
    'lastUpdated' : Time,
    'protocolId' : IDL.Text,
    'completedActions' : IDL.Vec(IDL.Text),
    'milestones' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  });
  const SystemMetric = IDL.Record({
    'id' : IDL.Text,
    'cycleUsage' : IDL.Nat,
    'userEngagement' : IDL.Nat,
    'timestamp' : Time,
    'aiProcessingTime' : IDL.Nat,
    'proofsPerDay' : IDL.Nat,
    'stakingTotals' : IDL.Nat,
  });
  const QuickAction = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'context' : IDL.Text,
    'usageCount' : IDL.Nat,
    'lastUsed' : Time,
  });
  const ScheduledNotification = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'scheduledTime' : Time,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'message' : IDL.Text,
    'sentimentIntensity' : IDL.Text,
  });
  const StakingPosition = IDL.Record({
    'startTime' : Time,
    'active' : IDL.Bool,
    'userId' : IDL.Principal,
    'amount' : IDL.Nat,
    'lockupPeriod' : IDL.Nat,
    'rewardMultiplier' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TourStep = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'target' : IDL.Text,
  });
  const TourProgress = IDL.Record({
    'userId' : IDL.Principal,
    'completed' : IDL.Bool,
    'lastUpdated' : Time,
    'steps' : IDL.Vec(TourStep),
  });
  const TransparencyLog = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'action' : IDL.Text,
    'userId' : IDL.Principal,
    'dataHash' : IDL.Text,
    'timestamp' : Time,
  });
  const UploadStatus = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'errorMessage' : IDL.Opt(IDL.Text),
    'filePath' : IDL.Text,
    'progress' : IDL.Nat,
    'timestamp' : Time,
  });
  const WearableConnection = IDL.Record({
    'service' : IDL.Text,
    'expiresAt' : IDL.Opt(Time),
    'refreshToken' : IDL.Opt(IDL.Text),
    'connectedAt' : Time,
    'accessToken' : IDL.Text,
  });
  const ZKProof = IDL.Record({
    'id' : IDL.Text,
    'verified' : IDL.Bool,
    'proofData' : IDL.Text,
    'userId' : IDL.Principal,
    'timestamp' : Time,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addAgentInteraction' : IDL.Func([AgentInteraction], [], []),
    'addBadge' : IDL.Func([Badge], [], []),
    'addCoachingSession' : IDL.Func([CoachingSession], [], []),
    'addDomainAgent' : IDL.Func([DomainAgent], [], []),
    'addExtractedData' : IDL.Func([IDL.Text, IDL.Vec(ExtractedField)], [], []),
    'addHealthIndicator' : IDL.Func([HealthIndicator], [], []),
    'addLeaderboardEntry' : IDL.Func([LeaderboardEntry], [], []),
    'addNotification' : IDL.Func([IDL.Principal, Notification], [], []),
    'addPartnerIntegration' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addReward' : IDL.Func([Reward], [], []),
    'addWhitePaperSection' : IDL.Func([IDL.Text, WhitePaperSection], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimReferralReward' : IDL.Func([IDL.Text], [], []),
    'completeOnboarding' : IDL.Func([], [], []),
    'connectWearable' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(Time)],
        [],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCustomCheckoutSession' : IDL.Func(
        [IDL.Vec(Product), IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCustomMetric' : IDL.Func([CustomMetric], [], []),
    'createHealthProtocol' : IDL.Func([HealthProtocol], [], []),
    'createProfessionalAccessToken' : IDL.Func(
        [ProfessionalAccessToken],
        [],
        [],
      ),
    'createReferral' : IDL.Func([IDL.Text], [], []),
    'createWhitePaperDocument' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteCheckoutSession' : IDL.Func([IDL.Text], [], []),
    'deleteHealthRecord' : IDL.Func([IDL.Text], [], []),
    'deletePaymentTransaction' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteUploadStatus' : IDL.Func([IDL.Text], [], []),
    'deleteWhitePaperDocument' : IDL.Func([IDL.Text], [], []),
    'deleteWhitePaperSection' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'getAIMemoryProfile' : IDL.Func([], [IDL.Opt(AIMemoryProfile)], ['query']),
    'getAgentInteractions' : IDL.Func(
        [],
        [IDL.Vec(AgentInteraction)],
        ['query'],
      ),
    'getAllReferrals' : IDL.Func([], [IDL.Vec(Referral)], ['query']),
    'getAllWhitePaperDocuments' : IDL.Func(
        [],
        [IDL.Vec(WhitePaperDocument)],
        ['query'],
      ),
    'getAnalyticsAggregates' : IDL.Func(
        [],
        [IDL.Vec(AnalyticsAggregate)],
        ['query'],
      ),
    'getBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
    'getBrandSuggestions' : IDL.Func([], [IDL.Vec(BrandSuggestion)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckoutSessionById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CheckoutSession)],
        ['query'],
      ),
    'getCheckoutSessions' : IDL.Func([], [IDL.Vec(CheckoutSession)], ['query']),
    'getCoachingSessions' : IDL.Func([], [IDL.Vec(CoachingSession)], ['query']),
    'getCommunityProposals' : IDL.Func(
        [],
        [IDL.Vec(CommunityProposal)],
        ['query'],
      ),
    'getCustomMetrics' : IDL.Func([], [IDL.Vec(CustomMetric)], ['query']),
    'getDashboardPreferences' : IDL.Func(
        [],
        [IDL.Opt(DashboardPreference)],
        ['query'],
      ),
    'getDomainAgents' : IDL.Func([], [IDL.Vec(DomainAgent)], ['query']),
    'getDomainProgress' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(HealthDomain, DomainProgress))],
        ['query'],
      ),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getGrantKPIs' : IDL.Func([], [IDL.Vec(GrantKPI)], ['query']),
    'getHealthIndicators' : IDL.Func([], [IDL.Vec(HealthIndicator)], ['query']),
    'getHealthProtocol' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(HealthProtocol)],
        ['query'],
      ),
    'getHealthRecordById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(HealthRecord)],
        ['query'],
      ),
    'getHealthRecords' : IDL.Func([], [IDL.Vec(HealthRecord)], ['query']),
    'getHelpPreferences' : IDL.Func([], [IDL.Opt(HelpPreference)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getLiquidityPools' : IDL.Func([], [IDL.Vec(LiquidityPool)], ['query']),
    'getNotificationPreferences' : IDL.Func(
        [],
        [IDL.Opt(NotificationPreference)],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPartnerIntegrations' : IDL.Func(
        [],
        [IDL.Vec(PartnerIntegration)],
        ['query'],
      ),
    'getPaymentTransactionById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PaymentTransaction)],
        ['query'],
      ),
    'getPaymentTransactions' : IDL.Func(
        [],
        [IDL.Vec(PaymentTransaction)],
        ['query'],
      ),
    'getPerformanceMetrics' : IDL.Func(
        [],
        [IDL.Vec(PerformanceMetric)],
        ['query'],
      ),
    'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProfessionalAccessToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProfessionalAccessToken)],
        ['query'],
      ),
    'getPromptSuggestions' : IDL.Func(
        [],
        [IDL.Vec(PromptSuggestion)],
        ['query'],
      ),
    'getProtocolProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProtocolProgress)],
        ['query'],
      ),
    'getPublicSystemMetrics' : IDL.Func([], [IDL.Vec(SystemMetric)], ['query']),
    'getQuickActions' : IDL.Func([], [IDL.Vec(QuickAction)], ['query']),
    'getReferral' : IDL.Func([IDL.Text], [IDL.Opt(Referral)], ['query']),
    'getRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
    'getScheduledNotifications' : IDL.Func(
        [],
        [IDL.Vec(ScheduledNotification)],
        ['query'],
      ),
    'getStakingPositions' : IDL.Func([], [IDL.Vec(StakingPosition)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSystemMetrics' : IDL.Func([], [IDL.Vec(SystemMetric)], ['query']),
    'getTourProgress' : IDL.Func([], [IDL.Opt(TourProgress)], ['query']),
    'getTransparencyLogs' : IDL.Func([], [IDL.Vec(TransparencyLog)], ['query']),
    'getUploadStatusById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UploadStatus)],
        ['query'],
      ),
    'getUploadStatuses' : IDL.Func([], [IDL.Vec(UploadStatus)], ['query']),
    'getUserHealthProtocols' : IDL.Func(
        [],
        [IDL.Vec(HealthProtocol)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWearableConnections' : IDL.Func(
        [],
        [IDL.Vec(WearableConnection)],
        ['query'],
      ),
    'getWhitePaperDocument' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WhitePaperDocument)],
        ['query'],
      ),
    'getZKProofs' : IDL.Func([], [IDL.Vec(ZKProof)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isBlackboardLocked' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOnboardingComplete' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'lockBlackboard' : IDL.Func([], [IDL.Text], []),
    'logTransparencyAction' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'processPayment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Text], []),
    'recordAnalyticsAggregate' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'recordGrantKPI' : IDL.Func([GrantKPI], [], []),
    'recordPerformanceMetric' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'recordSystemMetric' : IDL.Func([SystemMetric], [], []),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'revokeProfessionalAccessToken' : IDL.Func([IDL.Text], [], []),
    'saveAIMemoryProfile' : IDL.Func([AIMemoryProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDashboardPreferences' : IDL.Func([DashboardPreference], [], []),
    'saveHelpPreferences' : IDL.Func([HelpPreference], [], []),
    'saveNotificationPreferences' : IDL.Func([NotificationPreference], [], []),
    'savePromptSuggestions' : IDL.Func([IDL.Vec(PromptSuggestion)], [], []),
    'saveQuickActions' : IDL.Func([IDL.Vec(QuickAction)], [], []),
    'saveTourProgress' : IDL.Func([TourProgress], [], []),
    'scheduleNotification' : IDL.Func([ScheduledNotification], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'stakeTokens' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'submitBrandSuggestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'submitCommunityProposal' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitZKProof' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unlockBlackboard' : IDL.Func([], [IDL.Text], []),
    'unstakeTokens' : IDL.Func([IDL.Nat], [], []),
    'updateCheckoutSession' : IDL.Func([IDL.Text, CheckoutSession], [], []),
    'updateDomainProgress' : IDL.Func([HealthDomain, DomainProgress], [], []),
    'updateLiquidityPools' : IDL.Func([], [], []),
    'updatePaymentTransaction' : IDL.Func(
        [IDL.Text, PaymentTransaction],
        [],
        [],
      ),
    'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
    'updateProtocolProgress' : IDL.Func([ProtocolProgress], [], []),
    'updateReviewStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateUploadStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateWhitePaperSection' : IDL.Func(
        [IDL.Text, IDL.Text, WhitePaperSection],
        [],
        [],
      ),
    'updateWhitePaperStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'uploadHealthRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'voteOnProposal' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };